Single owner can manage delegates to mint
DappDevs/token pull request #2
Opened 2018-03-21 21:45 UTC by edgeoftheworld

removed voting functions, single owner who manages minters, owner can change faucet contract on token

2018-03-21 23:21 UTC, edgeoftheworld commented
here is the etherscan link to the deployed contract https://rinkeby.etherscan.io/address/0x29686429aad2b0674ed36a4d95b66c299dafc645

2018-03-22 00:00 UTC, fubuloubu commented
Some update suggestions:
1. Make the delegate data structure into a map e.g. `mapping (address => bool) public canMint`
NOTE `public` creates a getter:
```
// Automatically generated by solidity:
function canMint(address _delegate) public view returns (bool) {
    return canMint[_delegate];
}
```
2. `owner` can control delegate's minting abilities (through `canMint`)
3. Add an event to track changes to access rights (for UI) e.g:
`event AccessChanged(address delegate, bool canMint)`
4. Set `canMint` of `owner` to true in the constructor

2018-03-22 16:44 UTC, edgeoftheworld commented
updated contract on Rinkeby.  https://rinkeby.etherscan.io/address/0x5f1b069d88d239a52f51a6a7c5ecdfeec0afcbff

2018-03-23 03:51 UTC, fubuloubu requested changes

2018-03-23 03:51 UTC, fubuloubu commented on contracts/DappDevMint.sol
> +      emit AccessControl(newDelegate, true);
This is a new feature for v0.4.21, make sure the pragma reflects this

2018-03-23 03:51 UTC, fubuloubu commented on contracts/DappDevMint.sol
> +      emit AccessControl(newDelegate, true);
“‘emit’ keyword in Solidity” @AniketEngg https://medium.com/@aniketengg/emit-keyword-in-solidity-242a679b0e1a

2018-03-23 03:52 UTC, fubuloubu commented
Looking good! Will have to test next week!

2018-03-27 16:03 UTC, edgeoftheworld commented
compiler version changed.
https://rinkeby.etherscan.io/address/0x616f47efc6dcd6ca09c08426c7111c51a5dd2d10

2018-03-28 03:44 UTC, merged